volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/on/host
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/on/host

services:
  pressbooks:
    image: guard13007/pressbooks-compatible-wordpress-dockerfile:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
